/**
 * Smoke test for the Agent-mode shipping invariant:
 *   the Hermes bridge files AND its npm runtime deps MUST be declared as
 *   Tauri bundle resources, otherwise production .app builds ship without
 *   them and every Agent session silently fails to spawn (v1.1.0 / v1.1.2
 *   regression — see the v1.1.3 hotfix that added bridge/node_modules to
 *   resources).
 *
 * If any of these tests fail, the CI bundle won't have everything the
 * bridge needs under `Resources/bridge/` and `resolve_bridge_path()` /
 * `import @anthropic-ai/claude-agent-sdk` will fail at runtime in the
 * shipped .app.  Don't delete these without first proving the bridge is
 * shipped some other way (e.g., embedded).
 */

import { readFileSync, existsSync } from "fs";
import { describe, it, expect } from "vitest";

const TAURI_CONF = "src-tauri/tauri.conf.json";

describe("tauri.conf.json bundle resources", () => {
  const conf = JSON.parse(readFileSync(TAURI_CONF, "utf-8"));

  it("declares hermes-claude-bridge.mjs as a bundle resource", () => {
    const resources: string[] = conf?.bundle?.resources ?? [];
    expect(Array.isArray(resources)).toBe(true);
    const hasBridge = resources.some((r) =>
      r.includes("hermes-claude-bridge.mjs"),
    );
    expect(hasBridge).toBe(true);
  });

  it("declares canUseToolHelpers.mjs as a bundle resource", () => {
    const resources: string[] = conf?.bundle?.resources ?? [];
    const hasHelpers = resources.some((r) =>
      r.includes("canUseToolHelpers.mjs"),
    );
    expect(hasHelpers).toBe(true);
  });

  it("declares the bridge runtime node_modules as a bundle resource", () => {
    const resources: string[] = conf?.bundle?.resources ?? [];
    const hasNodeModules = resources.some((r) =>
      r === "bridge/node_modules" || r.startsWith("bridge/node_modules/"),
    );
    expect(hasNodeModules).toBe(true);
  });

  it("every static (non-generated) bridge resource exists on disk", () => {
    const resources: string[] = conf?.bundle?.resources ?? [];
    for (const r of resources) {
      // Generated by `npm run prepare:bridge`; skip the existence check
      // so this test works pre-build (CI runs unit tests before staging).
      if (r === "bridge/node_modules" || r.startsWith("bridge/node_modules/")) continue;
      const onDisk = `src-tauri/${r}`;
      expect(existsSync(onDisk), `expected ${onDisk} to exist`).toBe(true);
    }
  });

  it("triggers prepare:bridge as part of beforeBuildCommand", () => {
    // Without this the staged node_modules dir is missing whenever Tauri
    // builds the .app — the bug this whole pipeline exists to prevent.
    const cmd: string = conf?.build?.beforeBuildCommand ?? "";
    expect(cmd).toMatch(/prepare:bridge/);
  });
});

describe("bridge runtime package.json", () => {
  const root = JSON.parse(readFileSync("package.json", "utf-8"));
  const bridge = JSON.parse(
    readFileSync("src-tauri/bridge/package.json", "utf-8"),
  );

  it("pins the same Claude Agent SDK version as the root project", () => {
    const rootRange: string = root.dependencies["@anthropic-ai/claude-agent-sdk"];
    const bridgePin: string = bridge.dependencies["@anthropic-ai/claude-agent-sdk"];
    // Root uses a caret range (e.g. "^0.2.132"); the bridge pins the
    // exact base version so the bundled binary matches what is installed
    // in CI.  When you bump the SDK in root, also bump the bridge here.
    const rootBase = rootRange.replace(/^[\^~]/, "");
    expect(bridgePin).toBe(rootBase);
  });

  it("includes zod (peer dep of the SDK) so the bridge's `import { z } from 'zod'` resolves", () => {
    expect(bridge.dependencies?.zod).toBeTruthy();
  });
});
